Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd 	= GetCurrentDir()
src 	= []
CPPPATH = [cwd, str(Dir('#'))]

if GetDepend(['BSP_USING_MOTOR']):
	src += ['motor.c']
	src += ['pid.c']
	src += ['car_task.c']
	src += ['wheel.c']
	src += ['ps2.c']

group = DefineGroup('BoardDriver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
